from alist.pages.menu import Menu
from alist.pages.accueil import Accueil
from alist.pages.list_anime import ListAnime
from alist.pages.list_manga import ListManga
from alist.pages.my_anime import MyAnime
from alist.pages.my_manga import MyManga
from alist.pages.parameters import Parameters
from alist.pages.anime import Anime
from alist.pages.manga import Manga
from alist.pages.modif_anime import ModifAnime
from alist.pages.modif_manga import ModifManga
from alist.pages.stats import Stats
from alist.pages.news import News
from alist.pages.images import Images
from alist.pages.videos import Videos
